### ISSUE TITLE
Automatic signature search doesn't work after using "Rebase program"

### ISSUE THREAD

**Issue by SNMetamorph** [kweatherman/sigmakerex#6]
Looks like it's same issue as https://github.com/ajkhoury/SigMaker-x64/issues/31
Also fix for this bug is present there.

**Comment by kweatherman** [comment]
Thanks for reporting this.
Please give the latest [release](https://github.com/kweatherman/sigmakerex/releases/tag/1.1.2) a shot.

**Comment by SNMetamorph** [comment]
Yes it works now
