### ISSUE TITLE
Add test signature

### ISSUE THREAD

**Issue by marfixdev** [kweatherman/sigmakerex#7]
Please can you add "test signature" feature to check my patterns on IDA ?

**Comment by kweatherman** [comment]
I do think the original version of SigMaker has this feature, but
just use the "IDA" version, then "Binary Search" for it.

So say if your output looks like this:
```
SigMakerEx: Finding function signature.
Function SIG: 0x00549A50, 9 bytes 0, wildcards.
IDA: "57 68 04 01 00 00 6A 00 68"
"\x57\x68\x04\x01\x00\x00\x6A\x00\x68", "xxxxxxxxx"
```
You take the `57 68 04 01 00 00 6A 00 68` part and search like this:
![image](https://user-images.githubusercontent.com/76711484/203685648-de388613-9279-4689-b784-9dfe5e498bc9.png)

And you'll get all the matches (should normally be unique) like this:
![image](https://user-images.githubusercontent.com/76711484/203685739-276637af-8e5c-4123-b1ab-d16588d900ac.png)
