### ISSUE TITLE
[x64] RIP Relative LEA & MOV are not Wildcarded

### ISSUE THREAD

**Issue by Sewer56** [kweatherman/sigmakerex#9]
In x64 Assembly, it is possible to use LEA to get an address that's relative to the current instruction pointer; for example:

`48 8d 05 bc 32 2a 00    lea rax,[rip+0x2a32bc] `

In IDA this prints as: 

`48 8D 05 BC 32 2A 00  lea rax, aLabel`

This form of RIP relative addressing is often used to load static values, and/or constants. These are in other segments, thus not often stored at reliable offsets, and is thus unsafe. This should be wildcarded.

Edit: Applies to RIP relative MOV too

`48 89 05 2a f8 49 02    mov    QWORD PTR [rip+0x249f82a],rax`

**Comment by kweatherman** [comment]
Okay yea working on it.

The original SigMaker tool it was much looser as I recall. Tt would wildcard pretty much all numerical values. My philosophy is to keep more of them around to give signatures more integrity. To reduce the chance of false positives.  
Explicit/tight vs fuzzy/loose. Pros and cons for each range of the spectrum.

To me if I'm tracking some function for a game hacking project and like if it was a member function from a class you might see it accessing offsets into the class like `mov eax,[ecx+50h]`.  
If on an update some of the offsets change in the class. Like let's say they add a pointer in there then that same instruction becomes  `mov eax,[ecx+54h]` obviously if the pointer is inserted before.
I prefer this scenario as then my signature will fail telling me this member function has changed.

Now, on the other hand if you just wanted the numerical result of some function and you don't really care if the function has changed internally then it might be better to  `mov eax,[ecx+??]` wildcard the bytes.

An interesting part of this all is how small a signature can be, even over a large executable, to be unique. Just a few bytes past the prolog even. Maybe the majority of the time don't even need at lot of the value bytes. Would be interesting to make a statistical study that could point out more insights. 

Maybe I should add a config option for the later for a "fuzzy mode".

Anyhow, my algorithm examines values trying to determine if they are address locations or not and wild card them if they are.
I see the problem. AFAIK I think the simple solution if we see an "RIP + value", should wild card the value all the time.

**Comment by kweatherman** [comment]
Ah, no wonder why this hasn't come up before. Could not find a single indexed usage in several samples, then I searched through every "C:\Windows" executable. Surprisingly, I couldn't find a single instance. No "[rip" let alone "[rip+" et al. 
For what ever reason, the RIP instruction pattern is not used in the Microsoft pattern since it either creates large instructions and/or it's just not performant.

On a Nix executable? Gcc or? I'd need at least one binary with an indexed RIP to test with.

You know you can manually edit signatures right?  
For instance for this call instruction (relative address) it's hex is `E8 0C F7 FE FF`. Where the `E8` is the single byte instruction then the next four bytes make up the signed 32bit value call address. (Incidentally happens to be a negative value here since the address is above/lower than where the instruction is).  

To locate the value just look in the hex view in your disassembler and locate it the bytes in your signature. 
So in your example you should see "BC 32 2A 00". You can just eye ball it and search for say "2A" to find it in your signature probably. Then just replace at least three of the four bytes with the wildcard value and/or mask what ever output SigMakerEx output option you use.

Maybe at what your looking at has references but really if this a 0.001% problem I'm not sure it's worth even fixing..

**Comment by Sewer56** [comment]
It's not a very common pattern for compilers to emit in function prologues unless there's a reference to a static; but it does sometimes show up though.

After I noticed, I just wound up fixing the signatures by hand in the meantime, yep. 

In my case, I ran across it when working on x64 games employing CRI Middleware v2 FileSystem. Notably, on one of the APIs that require hooking to enable modding (loading custom files) for the games. This is a pretty common middleware used mainly by Japanese studios (you usually see it used in games published by SEGA, SqEnix, etc.)

If you'd like a sample binary or two, I'm happy to send. Or a slice of a binary that contains the affected opcodes (if needed).

**Comment by kweatherman** [comment]
Neat, I really like your work.
That system is used in a lot of console/handheld games huh?

It must be their particular toolchain I'd imagine. Being in Japan might be a clue. When I worked on console and handheld games  seems like they were all GNU tools.

Frankly, if it's such a tiny percent and I don't run into it my self I don't want to spend the time on it.
But, if you really want to add it yourself it would probably be in [AddInst()][https://github.com/kweatherman/sigmakerex/blob/master/Signature.cpp#L164]. 
Probably iterating the opcodes from the passed `insn_t` and if the register is "rip" then wildcard all value bytes if there are any.
Make an MR then I'll merge it.

**Comment by Sewer56** [comment]
I can give it a shot; I've never worked on an IDA Plugin before; but the README is pretty good, so I imagine I could give it a go once I figure out how to debug it.

Tooling wise, they're using standard MSVC settings; usually RIP relative operands tend to appear in middle of functions, rather than function prologues; though if there's an immediate access to a static, it'll usually appear. They often appear in getter methods.

Usually it's not a problem when generating signatures for functions, but when you're hooking particular middleware/libraries, a strategy I tend to employ is slightly extending the signature (by hand).

[Just because a signature is unique for current game, doesn't mean it's unique for another game, as there may be conflicts, so this helps handle unknown programs/games.]

I'll reboot to Windows (I daily drive Archlinux), and make a sample binary with C++ code that generates this instruction as a starting point.

**Comment by Sewer56** [comment]
Anyway, got the minimal repro.

It's as simple as:
```cpp
static int number = 42;
extern "C" __declspec(dllexport) int* RipRelativeLea() {
    return &number;
}

extern "C" __declspec(dllexport) int RipRelativeMov() {
    return number;
}
```

Source and Binaries: [MovLea.zip](https://github.com/kweatherman/sigmakerex/files/12706838/MovLea.zip)

![ida64_gHJu3pCHpJ](https://github.com/kweatherman/sigmakerex/assets/6697380/96434b89-d0b1-4723-b03c-fbf132fac291)

IDA presents this in a 'friendly' manner (as mentioned in first post), but these are RIP relative operations.

**Comment by Sewer56** [comment]
In a very strange twist of fate; I cannot reproduce this anymore.
Signatures are correctly being generated; and I tried on various disasms.

I was maybe working with a borked disasm; but in any case, the plugin seems to work correctly here.

**Comment by kweatherman** [comment]
Great okay. It happens. Live and learn.

**Comment by Sewer56** [comment]
Hanging on the edge of tomorrow 🎵
